### ISSUE TITLE
api 함수 signature 정비 + api docstring

### ISSUE THREAD

**Issue by holdonnn** [holdonnn/pouuch-api#197]
[GET] /posts
[POST] /users
를 참고하여 api 함수들의 signature와 docstring  리팩토링해주세요

**Comment by mindoool** [comment]
create_post(request_user_id, url, summary=None, is_secret=False):
update_post_by_id(post_id, request_user_id, summary=None, is_secret=None):

이렇게 수정하고 docs 내용도 업데이트함.
